# Generated by Django 5.0.6 on 2024-07-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Head_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_news', models.ImageField(upload_to='')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
    ]
