# Generated by Django 5.0.6 on 2024-07-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_post', models.ImageField(upload_to='')),
                ('info', models.TextField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
