# Generated by Django 5.0.6 on 2024-07-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_popular_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('user', models.CharField(max_length=255)),
                ('user_img', models.ImageField(upload_to='')),
                ('time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mini_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('txt', models.CharField(max_length=244)),
            ],
        ),
        migrations.CreateModel(
            name='News_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('glass', models.IntegerField()),
                ('img_post', models.ImageField(upload_to='')),
                ('time', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='popular_post',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
