# Generated by Django 5.0.6 on 2024-07-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comment_mini_news_news_all_alter_popular_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_all',
            name='title',
            field=models.CharField(default='', max_length=233),
            preserve_default=False,
        ),
    ]
