# Generated by Django 5.0.6 on 2024-07-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_all_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_all',
            name='info',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
